# Generated by Django 3.0.3 on 2020-04-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200423_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorized',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='CMCK60', max_length=6, primary_key=True, serialize=False),
        ),
    ]
