# Generated by Django 3.0.3 on 2020-04-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200423_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='GFS7Q2', max_length=6, primary_key=True, serialize=False),
        ),
    ]
