# Generated by Django 3.0.3 on 2020-04-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200423_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='authorized',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='EA6CB8', max_length=6, primary_key=True, serialize=False),
        ),
    ]
