# Generated by Django 3.0.3 on 2020-04-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sub_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
