# Generated by Django 3.0.3 on 2020-04-23 11:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subject_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
